[features]
seeds = false
skip-lint = false
[programs.localnet]
soliter = "2mCYvrwQNtUhCv626cwLfnco78pnGqVd6aNGZLvSKK7t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet" # localnet
wallet = "id.json" # 6Ea9ahava567TXjJaAXKiFmQNDjivDz55SWWRAcmcuBq

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
