[features]
seeds = false
skip-lint = false
[programs.localnet]
solanapdas = "BJCSLknaYyz6A8M3SQAtBUoR9xdcPxduLMTJ3UZBDdhN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet" # "Localnet"
wallet = "./id.json" # 6Ea9ahava567TXjJaAXKiFmQNDjivDz55SWWRAcmcuBq

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
